name: flutter_base_project
description: Scaffold project with all basic setup.

version: 1.0.0+2

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2

  easy_localization: ^1.3.1

  device_info: ^0.4.1+4

  package_info: ^0.4.0+13

  sentry: ^3.0.0+1

  url_launcher: ^5.4.1

  #Firebase
  firebase_crashlytics: ^0.1.2+4
  firebase_analytics: ^5.0.9
  firebase_performance: ^0.3.1+5
  firebase_remote_config: ^0.3.0+1

  performance_interceptor:
    git:
      url: git@gitlab.com:milind.mevada/firebase_performance_interceptor.git

  connectivity: ^0.4.6+1
  shared_preferences: ^0.5.6
  permission_handler: ^4.0.0
  cached_network_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.4.0


flutter:
  uses-material-design: true

  assets:
    # Localized strings
    - lib/assets/strings/
